name: Deploy Vue App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Clear all npm configuration
        run: npm config delete //registry.npmjs.org/:_authToken

      - name: Delete .npmrc from repository (if exists)
        run: rm -f .npmrc

      - name: Delete .npmrc from home directory (if exists)
        run: rm -f $HOME/.npmrc

      - name: Set npm registry to default
        run: npm config set registry https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install --no-optional

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
