name: Deploy Vue App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Grant write permission to the contents of the repo (to push to gh-pages)

    steps:
      - name: Clear npm cache
        run: npm cache clean --force

      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Add safe directory for git
        run: git config --global --add safe.directory /home/runner/work/robinj97.github.io/robinj97.github.io

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --registry=https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ''  # Ensure token is not set here

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use the default GitHub token
